[package]
name = "fem_rust"
version = "0.1.0"
authors = ["Hiroyuki Goto <goto@catfish.dpri.kyoto-u.ac.jp>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
